//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class BookshopEntities : DbContext
{
    public BookshopEntities()
        : base("name=BookshopEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
    public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
    public DbSet<aspnet_Paths> aspnet_Paths { get; set; }
    public DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
    public DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
    public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
    public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
    public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
    public DbSet<aspnet_Users> aspnet_Users { get; set; }
    public DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
    public DbSet<Book> Books { get; set; }
    public DbSet<Category> Categories { get; set; }
    public DbSet<IssueTran> IssueTrans { get; set; }
    public DbSet<IssueTransBookList> IssueTransBookLists { get; set; }
}
